# SPDX-License-Identifier: AGPL-3.0-or-later
# Targeted Trivy false-positive suppressions.
# Each entry suppresses a specific finding type in a specific file only.
# Add entries only for confirmed non-credentials with a filed upstream reference.
