// SPDX-License-Identifier: AGPL-3.0-or-later
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

import { beforeAll, describe, expect, it } from "vitest";

import { workspacePrincipal } from "./index";

/**
 * Mock-free SSH e2e against a workspace node running standard OpenSSH sshd
 * (docker-compose.ssh.yml). The test harness generates an ephemeral user
 * certificate signed by the CA that scripts/gen-ssh-ca.sh created, then
 * connects with standard ssh and asserts:
 *
 *  1. Session lands on the node as the principal workspacePrincipal derives.
 *  2. A login not listed in the node's AuthorizedPrincipalsFile is denied.
 *
 * Auth is certificate-based (our own CA), RBAC is via
 * AuthorizedPrincipalsFile in the sshd_config.
 */

const NODE_HOST = "localhost";
const NODE_PORT = "2222";
// Principal must equal workspacePrincipal("e2e") and the entry in
// /etc/ssh/principals/dev-e2e inside the workspace-node container.
const PRINCIPAL = workspacePrincipal("e2e");

// The CA private key was generated by scripts/gen-ssh-ca.sh into temp/ssh-ca/
// before the container started. The CA public key is mounted into the container
// as TrustedUserCAKeys. temp/ is gitignored.
const TEMP = join(process.cwd(), "temp", "ssh-ca");
const CA_KEY = join(TEMP, "ca");
const USER_KEY = join(TEMP, "e2e-id");

function run(cmd: string, args: string[]): { status: number; stdout: string; stderr: string } {
  const res = spawnSync(cmd, args, { encoding: "utf8" });
  if (res.error) throw res.error;
  // spawnSync status is number|null; -1 signals that the child never started.
  // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
  return { status: res.status === null ? -1 : res.status, stdout: res.stdout, stderr: res.stderr };
}

function ssh(...args: string[]) {
  return run("ssh", [
    "-i",
    USER_KEY,
    "-o",
    "StrictHostKeyChecking=no",
    "-o",
    "UserKnownHostsFile=/dev/null",
    "-p",
    NODE_PORT,
    ...args,
  ]);
}

describe("SSH to a workspace (mock-free, standard sshd + certificate auth)", () => {
  beforeAll(() => {
    mkdirSync(TEMP, { recursive: true });

    // Generate an ephemeral user key pair for this test run.
    run("ssh-keygen", ["-q", "-t", "ed25519", "-N", "", "-f", USER_KEY, "-C", "edd-e2e-user"]);

    // Sign the user public key with our CA. The resulting cert (USER_KEY-cert.pub)
    // is picked up automatically by ssh when -i USER_KEY is specified.
    // -n PRINCIPAL  the SSH principal the cert grants (must match principals file)
    // -V +1h        TTL: short-lived, appropriate for test use
    // -I            key identity label (audit log only)
    const signed = run("ssh-keygen", [
      "-s",
      CA_KEY,
      "-I",
      "edd-e2e-tester",
      "-n",
      PRINCIPAL,
      "-V",
      "+1h",
      `${USER_KEY}.pub`,
    ]);
    if (signed.status !== 0) {
      throw new Error(`ssh-keygen cert sign failed:\n${signed.stderr}`);
    }
  });

  it("connects to the workspace node as the derived principal", () => {
    // -tt forces PTY allocation even when stdin is not a terminal (CI / spawnSync).
    // Tests that the workspace node accepts interactive sessions, which VS Code
    // Server terminal requires.
    const res = ssh("-tt", `${PRINCIPAL}@${NODE_HOST}`, "whoami");
    expect(res.status, `${res.stdout}${res.stderr}`).toBe(0);
    expect(res.stdout.trim()).toBe(PRINCIPAL);
  });

  it("denies a login the principals file does not grant", () => {
    // root is not listed in /etc/ssh/principals/root, so sshd rejects the cert.
    const res = ssh(`root@${NODE_HOST}`, "whoami");
    expect(res.status, "root login should be denied").not.toBe(0);
  });
});
