// SPDX-License-Identifier: AGPL-3.0-or-later
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
  baseImage,
  FakeComputeProvider,
  FakeStorageProvider,
  ownerId,
  systemClock,
  workspaceId,
  workspacePrincipal,
} from "@edd/core";
import { WorkspaceService } from "@edd/control-plane";
import { createDynamoClient, dropTable, ensureTable, makeWorkspaceEntity } from "@edd/db";
import { dynamodbLocal } from "@edd/config";

/**
 * Full user-journey e2e: create workspace → issue SSH cert → SSH connect →
 * heartbeat → stop → wake via connect().
 *
 * Uses FakeComputeProvider (no ECS) + real DynamoDB Local. The SSH leg
 * connects to the workspace node from docker-compose.ssh.yml (localhost:2222).
 *
 * The cert is signed via the same CA that gen-ssh-ca.sh generates before the
 * harness starts (same as ssh-connect.e2e.ts).
 *
 * Proxy-to-workspace-container forwarding is tested separately against the
 * container-mode sim.
 */

const TABLE = "ecs-dev-desktop-user-journey-e2e";
const NODE_HOST = "localhost";
const NODE_PORT = "2222";

// The workspace node (docker-compose.ssh.yml) has OS user "dev-e2e" with
// principal "dev-e2e" in its principals file.
const JOURNEY_PRINCIPAL = workspacePrincipal("e2e"); // "dev-e2e"

// CA key is generated by gen-ssh-ca.sh into services/ssh-gateway/temp/ssh-ca/
// (relative to the repo root). import.meta.dirname is packages/e2e/src, so
// ../../.. reaches the repo root.
const SSH_CA_DIR = join(import.meta.dirname, "../../../services/ssh-gateway/temp/ssh-ca");
const CA_KEY = join(SSH_CA_DIR, "ca");
// Per-test user key goes alongside the CA (same gitignored temp dir).
const USER_KEY = join(SSH_CA_DIR, "journey-id");

process.env.DYNAMODB_ENDPOINT ??= dynamodbLocal.endpoint;

function run(cmd: string, args: string[]): { status: number; stdout: string; stderr: string } {
  const res = spawnSync(cmd, args, { encoding: "utf8" });
  if (res.error) throw res.error;
  return { status: res.status ?? -1, stdout: res.stdout, stderr: res.stderr };
}

function ssh(...args: string[]): { status: number; stdout: string; stderr: string } {
  return run("ssh", [
    "-i",
    USER_KEY,
    "-o",
    "StrictHostKeyChecking=no",
    "-o",
    "UserKnownHostsFile=/dev/null",
    "-p",
    NODE_PORT,
    ...args,
  ]);
}

describe(
  "User journey: workspace lifecycle + SSH cert issuance + SSH connect",
  { timeout: 60_000 },
  () => {
    let service: WorkspaceService;
    let wsId: string;

    beforeAll(async () => {
      // Generate a per-run user key pair.
      run("ssh-keygen", [
        "-q",
        "-t",
        "ed25519",
        "-N",
        "",
        "-f",
        USER_KEY,
        "-C",
        "edd-journey-user",
      ]);

      // Sign the user key with the workspace CA to produce a cert for JOURNEY_PRINCIPAL.
      const signed = run("ssh-keygen", [
        "-s",
        CA_KEY,
        "-I",
        "edd-journey-tester",
        "-n",
        JOURNEY_PRINCIPAL,
        "-V",
        "+1h",
        `${USER_KEY}.pub`,
      ]);
      if (signed.status !== 0) throw new Error(`ssh-keygen sign failed: ${signed.stderr}`);

      const storage = await FakeStorageProvider.create();
      // FakeComputeProvider returns sshHost "localhost" — proves the field is stored.
      const compute = new FakeComputeProvider(storage, { sshHost: "localhost" });
      const client = createDynamoClient();
      await dropTable(client, TABLE);
      await ensureTable(client, TABLE);
      service = new WorkspaceService({
        workspaces: makeWorkspaceEntity(client, TABLE),
        storage,
        compute,
        clock: systemClock,
      });
    });

    afterAll(async () => {
      const client = createDynamoClient();
      await dropTable(client, TABLE);
    });

    it("creates a workspace in state 'running'", async () => {
      const ws = await service.create({
        ownerId: ownerId("journey-user"),
        baseImage: baseImage("golden/node:20"),
      });
      expect(ws.state).toBe("running");
      wsId = ws.id;
    });

    it("cert is valid and contains the expected principal", () => {
      const certFile = `${USER_KEY}-cert.pub`;
      const cert = readFileSync(certFile, "utf8");
      expect(cert).toMatch(/^ssh-ed25519-cert-v01@openssh\.com /);

      const inspect = run("ssh-keygen", ["-L", "-f", certFile]);
      expect(inspect.stdout).toContain(JOURNEY_PRINCIPAL);
    });

    it("SSHes to the workspace node using the issued cert", () => {
      const res = ssh("-tt", `${JOURNEY_PRINCIPAL}@${NODE_HOST}`, "whoami");
      expect(res.status, `SSH failed:\n${res.stdout}${res.stderr}`).toBe(0);
      expect(res.stdout.trim()).toBe(JOURNEY_PRINCIPAL);
    });

    it("heartbeat keeps the workspace active", async () => {
      const result = await service.heartbeat(workspaceId(wsId));
      expect(result.ok).toBe(true);
      if (result.ok) expect(result.value.state).toBe("running");
    });

    it("stop() transitions to stopped", async () => {
      const result = await service.stop(workspaceId(wsId));
      expect(result.ok).toBe(true);
      if (result.ok) expect(result.value.state).toBe("stopped");
    });

    it("connect() wakes the stopped workspace (wake-on-connect)", async () => {
      const result = await service.connect(workspaceId(wsId));
      expect(result.ok).toBe(true);
      if (result.ok) expect(result.value.state).toBe("running");
    });

    it("SSH succeeds again after wake-on-connect", () => {
      const res = ssh("-tt", `${JOURNEY_PRINCIPAL}@${NODE_HOST}`, "whoami");
      expect(res.status, `SSH after wake failed:\n${res.stdout}${res.stderr}`).toBe(0);
      expect(res.stdout.trim()).toBe(JOURNEY_PRINCIPAL);
    });
  },
);
